fa-solid fa-house
fa-solid fa-table-columns
fa-solid fa-users
fa-solid fa-user
fa-solid fa-user-plus
fa-solid fa-right-from-bracket
fa-solid fa-right-to-bracket
fa-solid fa-gear
fa-solid fa-envelope
fa-solid fa-plus
fa-solid fa-xmark
fa-solid fa-check
fa-solid fa-pen
fa-solid fa-trash
fa-solid fa-grip-vertical
fa-solid fa-ellipsis-vertical
fa-solid fa-circle-info
fa-solid fa-triangle-exclamation
fa-solid fa-magnifying-glass
fa-solid fa-bars
fa-solid fa-sun
fa-solid fa-moon
fa-solid fa-chevron-down
fa-solid fa-chevron-right
fa-solid fa-arrow-right
fa-solid fa-tag
fa-solid fa-list-check
fa-solid fa-comment
fa-solid fa-paperclip
fa-solid fa-calendar
fa-solid fa-floppy-disk
fa-solid fa-circle-xmark
fa-regular fa-copy
